" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim
" (usually just /usr/share/vim/vimfiles/archlinux.vim) and sourced by
" the call to :runtime you can find below. If you wish to change any
" of those settings, you should do it in this file (/etc/vimrc), since
" archlinux.vim will be overwritten everytime an upgrade of the vim
" packages is performed.  It is recommended to make changes after
" sourcing archlinux.vim since it alters the value of the 'compatible'
" option.

" This line should not be removed as it ensures that various options
" are properly set to work with the Vim-related packages.
runtime! archlinux.vim

colorscheme koehler

set sts=4 ts=4 sw=4 noet noai nocin nosi inde= number encoding=utf-8
filetype indent plugin off
:autocmd Filetype * set sts=4 ts=4 sw=4 noet noai nocin nosi inde=
:autocmd Filetype * set number encoding=utf-8
:autocmd Filetype * filetype indent plugin off

